### ISSUE TITLE
некоторые пункты можно обновить?

### ISSUE THREAD

**Issue by SergeiSmazheluk** [AnzhelikaKravchuk/.NET-Training.-Spring-2019#24]
![image](https://user-images.githubusercontent.com/89450398/145991770-bde889e9-7934-4fbb-b6b8-275116018f36.png)
в структурах нельзя использовать virtual
пункт про конструкторы без параметров обновить необходимо:
![image](https://user-images.githubusercontent.com/89450398/145994389-b93b75d0-67a2-4462-9f75-6a207da6e580.png)

**Comment by SergeiSmazheluk** [comment]
В пункте о различиях между интерфейсом и абстрактным классом:

![image](https://user-images.githubusercontent.com/89450398/146118379-b9dc8083-de9a-4bd6-83e9-e36bdce1f1eb.png)

**Comment by AnzhelikaKravchuk** [comment]
Спасибо за замечания, но, возможно вы успели заметить, этот репозиторий уже не поддерживается, тренинг переехал.
